CC=clang
PRESENT_DIRECTORY = $(filter %/, $(wildcard ./*/))
CFLAGS=-g -D_GNU_SOURCE -Wall
MP=./Misc_Utils/
DSP=./Data_Structures/
LDFLAGS=-pthread
FLAGS=$(CFLAGS) $(LDFLAGS)
SOURCES=MU_Logger.c MU_Arg_Check.c MU_Cond_Locks.c DS_Hash_Map.c DS_Hash_Map_Test.c
OBJECTS=$(notdir $(SOURCES:.c=.o))
TARGET=DS_Hash_Map_Test
DEPS=$(addprefix -I, $(PRESENT_DIRECTORY))
VPATH=$(MP) $(DSP)
MAKEDEPEND=gcc -M $(CFLAGS) -o $*.d %<

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) $(DEPS) $(OBJECTS) -o $(TARGET) $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) $(DEPS) -c $< -o $@

.PHONY: depend clean

depend: $(SOURCES)
	makedepend $(DEPS) $^

clean: 
	$(RM) $(TARGET) *.o *~

# DO NOT DELETE THIS LINE -- make depend depends on it.

./Misc_Utils/MU_Logger.o: ./Misc_Utils/MU_Logger.h /usr/include/stdio.h
./Misc_Utils/MU_Logger.o: /usr/include/_ansi.h /usr/include/newlib.h
./Misc_Utils/MU_Logger.o: /usr/include/sys/config.h
./Misc_Utils/MU_Logger.o: /usr/include/machine/ieeefp.h
./Misc_Utils/MU_Logger.o: /usr/include/sys/features.h
./Misc_Utils/MU_Logger.o: /usr/include/sys/cdefs.h
./Misc_Utils/MU_Logger.o: /usr/include/machine/_default_types.h
./Misc_Utils/MU_Logger.o: /usr/include/sys/reent.h /usr/include/sys/_types.h
./Misc_Utils/MU_Logger.o: /usr/include/machine/_types.h
./Misc_Utils/MU_Logger.o: /usr/include/sys/lock.h /usr/include/sys/types.h
./Misc_Utils/MU_Logger.o: /usr/include/sys/_stdint.h
./Misc_Utils/MU_Logger.o: /usr/include/machine/types.h
./Misc_Utils/MU_Logger.o: /usr/include/sys/stdio.h /usr/include/stdlib.h
./Misc_Utils/MU_Logger.o: /usr/include/machine/stdlib.h /usr/include/alloca.h
./Misc_Utils/MU_Logger.o: /usr/include/errno.h /usr/include/sys/errno.h
./Misc_Utils/MU_Logger.o: /usr/include/string.h /usr/include/sys/string.h
./Misc_Utils/MU_Logger.o: /usr/include/time.h /usr/include/machine/time.h
./Misc_Utils/MU_Logger.o: /usr/include/sys/timespec.h
./Misc_Utils/MU_Logger.o: /usr/include/sys/_timespec.h /usr/include/assert.h
./Misc_Utils/MU_Arg_Check.o: ./Misc_Utils/MU_Arg_Check.h
./Misc_Utils/MU_Arg_Check.o: ./Misc_Utils/MU_Logger.h /usr/include/stdio.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/_ansi.h /usr/include/newlib.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/sys/config.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/machine/ieeefp.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/sys/features.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/sys/cdefs.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/machine/_default_types.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/sys/reent.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/sys/_types.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/machine/_types.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/sys/lock.h /usr/include/sys/types.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/sys/_stdint.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/machine/types.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/sys/stdio.h /usr/include/stdlib.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/machine/stdlib.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/alloca.h /usr/include/errno.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/sys/errno.h /usr/include/string.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/sys/string.h /usr/include/time.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/machine/time.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/sys/timespec.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/sys/_timespec.h
./Misc_Utils/MU_Arg_Check.o: /usr/include/assert.h
./Misc_Utils/MU_Cond_Locks.o: ./Misc_Utils/MU_Cond_Locks.h
./Misc_Utils/MU_Cond_Locks.o: ./Misc_Utils/MU_Logger.h /usr/include/stdio.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/_ansi.h /usr/include/newlib.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/config.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/machine/ieeefp.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/features.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/cdefs.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/machine/_default_types.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/reent.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/_types.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/machine/_types.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/lock.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/types.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/_stdint.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/machine/types.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/stdio.h /usr/include/stdlib.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/machine/stdlib.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/alloca.h /usr/include/errno.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/errno.h /usr/include/string.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/string.h /usr/include/time.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/machine/time.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/timespec.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sys/_timespec.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/assert.h /usr/include/pthread.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/signal.h /usr/include/sys/signal.h
./Misc_Utils/MU_Cond_Locks.o: /usr/include/sched.h /usr/include/sys/sched.h
./Data_Structures/DS_Hash_Map.o: ./Data_Structures/DS_Hash_Map.h
./Data_Structures/DS_Hash_Map.o: ./Data_Structures/DS_Helpers.h
./Data_Structures/DS_Hash_Map.o: /usr/include/stdint.h
./Data_Structures/DS_Hash_Map.o: /usr/include/machine/_default_types.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/features.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/_intsup.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/_stdint.h
./Data_Structures/DS_Hash_Map.o: /usr/include/stdio.h /usr/include/_ansi.h
./Data_Structures/DS_Hash_Map.o: /usr/include/newlib.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/config.h
./Data_Structures/DS_Hash_Map.o: /usr/include/machine/ieeefp.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/cdefs.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/reent.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/_types.h
./Data_Structures/DS_Hash_Map.o: /usr/include/machine/_types.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/lock.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/types.h
./Data_Structures/DS_Hash_Map.o: /usr/include/machine/types.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/stdio.h
./Data_Structures/DS_Hash_Map.o: /usr/include/stdlib.h
./Data_Structures/DS_Hash_Map.o: /usr/include/machine/stdlib.h
./Data_Structures/DS_Hash_Map.o: /usr/include/alloca.h /usr/include/errno.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/errno.h
./Data_Structures/DS_Hash_Map.o: /usr/include/string.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/string.h
./Data_Structures/DS_Hash_Map.o: ./Misc_Utils/MU_Logger.h /usr/include/time.h
./Data_Structures/DS_Hash_Map.o: /usr/include/machine/time.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/timespec.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/_timespec.h
./Data_Structures/DS_Hash_Map.o: /usr/include/assert.h
./Data_Structures/DS_Hash_Map.o: ./Misc_Utils/MU_Cond_Locks.h
./Data_Structures/DS_Hash_Map.o: /usr/include/pthread.h /usr/include/signal.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/signal.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sched.h
./Data_Structures/DS_Hash_Map.o: /usr/include/sys/sched.h
./Data_Structures/DS_Hash_Map.o: ./Misc_Utils/MU_Arg_Check.h
./Data_Structures/DS_Hash_Map_Test.o: ./Data_Structures/DS_Hash_Map.h
./Data_Structures/DS_Hash_Map_Test.o: ./Data_Structures/DS_Helpers.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/stdint.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/machine/_default_types.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/features.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/_intsup.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/_stdint.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/stdio.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/_ansi.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/newlib.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/config.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/machine/ieeefp.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/cdefs.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/reent.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/_types.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/machine/_types.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/lock.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/types.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/machine/types.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/stdio.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/stdlib.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/machine/stdlib.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/alloca.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/errno.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/errno.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/string.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/string.h
./Data_Structures/DS_Hash_Map_Test.o: ./Misc_Utils/MU_Logger.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/time.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/machine/time.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/timespec.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/_timespec.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/assert.h
./Data_Structures/DS_Hash_Map_Test.o: ./Misc_Utils/MU_Cond_Locks.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/pthread.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/signal.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/signal.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sched.h
./Data_Structures/DS_Hash_Map_Test.o: /usr/include/sys/sched.h
./Data_Structures/DS_Hash_Map_Test.o: ./Misc_Utils/MU_Arg_Check.h
